Update firebase-distribution.yml

diff --git a/.github/workflows/firebase-distribution.yml b/.github/workflows/firebase-distribution.yml
--- a/.github/workflows/firebase-distribution.yml
+++ b/.github/workflows/firebase-distribution.yml
@@ -22,6 +22,17 @@ jobs:
           
       - name: Navigate to Flutter project directory
         run: cd flutter-project/skill_swap  # Navigate to the skill_swap directory
+
+      - name: Print working directory
+        run: pwd
+
+      - name: Check if pubspec.yaml exists
+        run: |
+          if [ ! -f pubspec.yaml ]; then
+            echo "Error: pubspec.yaml not found!" && exit 1
+          else
+            echo "pubspec.yaml found."
+          fi
       
       - name: Install Dependencies
         run: flutter pub get
